server:
  port: 9099

spring:
  redis:
    host: 193.112.19.133
    port: 6379
    password: java1907
    jedis:
      pool:
        max-active: 66
  rabbitmq:
    host: 193.112.19.133
    port: 5672
    username: java1907
    password: 123
    virtual-host: java1907

  datasource:
    url: jdbc:mysql://123.207.253.16:3306/miaoshawu?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml

dubbo:
  application:
    name: web-miaosha
  registry:
    protocol: zookeeper
    address: 193.112.19.133:2181