dubbo:
  application:
    name: web-center
  registry:
    protocol: zookeeper
    address: 193.112.19.133:2181
server:
  port: 9090
spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
  rabbitmq:
    host: 193.112.19.133
    port: 5672
    username: java1907
    password: 123
    virtual-host: java1907
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 193.112.19.133:22122
image:
  server: http://193.112.19.133/



