spring:
  servlet:
    multipart:
      max-file-size: 10MB
  rabbitmq:
    host: 193.112.19.133
    port: 5672
    username: java1907
    password: 123
    virtual-host: java1907
dubbo:
  application:
    name: sms-service
  registry:
    protocol: zookeeper
    address: 193.112.19.133:2181
  protocol:
    port: 28813
server:
  port: 8094