spring:
  mail:
    host: smtp.qq.com
    username: 2624327119@qq.com
    password: ssqpwfrbczdqechi
    default-encoding: UTF-8

mail:
  fromAddr: 2624327119@qq.com
dubbo:
  application:
    name: search-service
  registry:
    protocol: zookeeper
    address: 193.112.19.133:2181
  protocol:
    port: 28816
server:
  port: 8096